### ISSUE TITLE
[BUG] Get user-defined sieve working (global sieve is OK)

### ISSUE THREAD

**Issue by cybermcm** [docker-mailserver/docker-mailserver#1280]
Can't get sieve rules working

## Context
Working with the latest docker-mailserver container. Trying to get sieve rule working (simple rule moving mails with a from address to another folder)

## Expected Behavior
mail gets moved

## Actual Behavior
mail gets to inbox

## Possible Fix
none found

## Steps to Reproduce
created .dovecot.sieve within /var/mail/domain/user
```
require ["fileinto"];

if header :contains ["From"] "mail@domain.net" {
   fileinto "Archive";
} else {
     keep;
}
```
mail still is delivered to inbox. Archive folder exists

tried rainloop with Managed Sieve. First error message:
```
mail dovecot: managesieve(xxx)<29434><BYcCTuqTwpqsEgAL>: Error: sieve: file storage: mkdir_parents_chgrp(/home/users/xxx/sieve/tmp) failed: Permission denied (euid=5000(docker) egid=5000(docker) missing +w perm: /home, dir owned by 0:0 mode=0755)
Oct  2 11:43:44 mail dovecot: managesieve(xxx)<29434><BYcCTuqTwpqsEgAL>: Fatal: Failed to open Sieve storage.
```
If I change permissions within the docker container I can get sieve working with rainloop but that is not really a solution (after every update I'd have to set permissions again or redirect folder to host)

## Your Environment
mailserver: latest tag
config:
```
mail:
  cap_add:
   - NET_ADMIN # needed by fail2ban inside container
   #- SYS_PTRACE # not clear if needed https://github.com/tomav/docker-mailserver/issues/1057
  container_name: mail
  depends_on:
   - openldap
  domainname: ${hostname}
  env_file: /opt/.env
  environment:
   - DMS_DEBUG=0
   - ENABLE_CLAMAV=1
   - ONE_DIR=1
   - ENABLE_POP3=1
   - ENABLE_FAIL2BAN=1
   - SSL_TYPE=manual
   - SSL_CERT_PATH=${mail_SSL_CERT_PATH}
   - SSL_KEY_PATH=${mail_SSL_KEY_PATH}
   - TLS_LEVEL=modern
   - SPOOF_PROTECTION=1
   - ENABLE_SRS=0
   - PERMIT_DOCKER=network   
   - POSTFIX_MESSAGE_SIZE_LIMIT=30720000
   - ENABLE_MANAGESIEVE=1
   - OVERRIDE_HOSTNAME=${mail_OVERRIDE_HOSTNAME}
   - PFLOGSUMM_TRIGGER=daily_cron
   #- PFLOGSUMM_RECIPIENT=${mail_PFLOGSUMM_RECIPIENT}
   - LOGWATCH_INTERVAL=daily
   - ENABLE_SPAMASSASSIN=1
   - ENABLE_LDAP=1
   - LDAP_START_TLS=no
   - LDAP_SERVER_HOST=${mail_LDAP_SERVER_HOST}
   - LDAP_SEARCH_BASE=${mail_LDAP_SEARCH_BASE}
   - LDAP_BIND_DN=${mail_LDAP_BIND_DN}
   - LDAP_BIND_PW=${mail_LDAP_BIND_PW}
   - LDAP_QUERY_FILTER_USER=${mail_LDAP_QUERY_FILTER_USER}
   - LDAP_QUERY_FILTER_GROUP=${mail_LDAP_QUERY_FILTER_GROUP}
   - LDAP_QUERY_FILTER_ALIAS=${mail_LDAP_QUERY_FILTER_ALIAS}
   - LDAP_QUERY_FILTER_DOMAIN=${mail_LDAP_QUERY_FILTER_DOMAIN}
   - DOVECOT_USER_FILTER=${mail_DOVECOT_USER_FILTER}
   - DOVECOT_PASS_FILTER=${mail_DOVECOT_PASS_FILTER}
   - ENABLE_POSTGREY=0
   - ENABLE_SASLAUTHD=1
   - SASLAUTHD_MECHANISMS=ldap
   - SASLAUTHD_LDAP_SERVER=${mail_SASLAUTHD_LDAP_SERVER}
   - SASLAUTHD_LDAP_SSL=0
   - SASLAUTHD_LDAP_BIND_DN=${mail_SASLAUTHD_LDAP_BIND_DN}
   - SASLAUTHD_LDAP_PASSWORD=${mail_SASLAUTHD_LDAP_PASSWORD}
   - SASLAUTHD_LDAP_SEARCH_BASE=${mail_SASLAUTHD_LDAP_SEARCH_BASE}
   - SASLAUTHD_LDAP_FILTER=${mail_SASLAUTHD_LDAP_FILTER}
  hostname: ${mail_hostname}
  image: tvial/docker-mailserver
  labels:
   - ${ouro_true}
  networks:
   compose:
    # fixed ip to use it from the host machine
    ipv4_address: 172.18.1.1
  ports:
   - "25:25"
   - "587:587"
   - "993:993"
   - "995:995"
   #- "4190:4190"
  restart: always
  volumes:
   - ${timezone}
   - ${localtime}
   - /opt/_ssl:/tmp/ssl:ro
   - /opt/mail/var:/var/mail
   - /opt/mail/state:/var/mail-state
   - /opt/mail/config:/tmp/docker-mailserver
   - /opt/mail/log:/var/log/mail
   - /opt/mail/opendmarc:/etc/opendmarc
```

## Possible answers to you issue
none found

**Comment by erik-wramner** [comment]
Has this worked before (if so when) or is it your first attempt?

**Comment by cybermcm** [comment]
This is my first attempt. Tried the simplest possible version ;-) but no luck...

**Comment by erik-wramner** [comment]
Right. In that case it is probably not a bug as others have sieve working. I don't use it myself, so I'm flagging it help wanted. Hopefully someone will see the post and help out.

**Comment by cybermcm** [comment]
Thank you for that, maybe just a small glitch but currently I don't manage to get this working....

**Comment by svheel** [comment]
Looking at my sieve-configuration (created by the managesieve plugin from Roundcubemail), try removing the '[]' in the if statement and use lower-case (not sure if that matters), so:
```
require ["fileinto"];

if header :contains "from" "mail@domain.net" {
   fileinto "Archive";
} else {
     keep;
}
```

I'm not sure how to exactly configure Rainloop, this is what I have in my Roundcubemail configuration:
```
<?php
    $config['managesieve_port'] = 4190;
    $config['managesieve_host'] = 'tls://mail';
    $config['managesieve_conn_options'] = array('verify_peer_name' => false) );
```

So connect with TLS to port 4190 of the 'mail' container ('mail' is the name of the container for docker-mailserver, it's resolved by Docker to the correct IP) and turn of verifying of the peer-name.

This way I can configure the sieve-filters from within Roundcube.
Judging from screenshots around the internet, for Rainloop open 'Sieve Configuration' from the domain-screen and fill in 'mail' for server and '4190' for port. Play around with the 'Secure' dropbox until it works, I'm guessing you have to select 'TLS'.
Hope this helps!

**Comment by cybermcm** [comment]
@svheel: thanks for you answer but it didn't work.
If I put a .dovecot.sieve within /var/mail/domain/user I think it is simply ignored, I could find no evidence that it gets used, I tried different sieve rules.
If I use the Managedsieve solution if have different error messages. Rainloop searches in /home/user/... a folder which doesn't exist in this docker container.
Currently I think sieve rules are broken or the Wiki article isn't correct any more. Still curious if someone managed to get this working....

**Comment by wernerfred** [comment]
Hi
do you really have your config like shown in your post?
```
 ports:
   - "25:25"
   - "587:587"
   - "993:993"
   - "995:995"
   #- "4190:4190"
 restart: always
```
How should rainloop (or whatever tool you use) be able to connect to sieve if the port ist not forwarded?

My rainloop places its sieve configuration under ```/var/mail/domain.tld/user/sieve/rainloop.user.sieve```

Permissions:
```
root@mail:/var/mail/domain.tld/user/sieve# ls -la
total 32
drwx------  3 docker docker  4096 Feb 10 14:49 .
drwx------ 25 docker docker  4096 Feb 18 09:15 ..
-rw-------  1 docker docker 18589 Feb 10 14:17 rainloop.user.sieve
drwx------  2 docker docker  4096 Feb 10 14:49 tmp
```

And a rule looks like this:
```
require ["fileinto"];

if anyof(
    header :contains ["To", "CC"] "user-github@domain.tld",
    header :contains ["From"] "notifications@github.com"
)
{
    fileinto "Server";
    stop;
}
```
So compared to your example rainloop creates a ```stop;``` after the ```fileinto "Folder"``` action. Maybe try this if it works for you

**Comment by cybermcm** [comment]
@wernerfred Thx for your reply.
ports: my mail container and my rainloop container share the same docker network, so no need to publish my sieve port. In the rainloop admin portal the sieve test shows success.

But my main goal is to achieve sieve within the mail container itself and this is still not working (no error message and no message about sieve at all). I just checked the wiki again and still no luck. It seems that sieve isn't working

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.

**Comment by cybermcm** [comment]
@aendeavor: I understand that issues can't be open forever but this is still open or at least the documentation has some issue or it is just me doing something wrong...

**Comment by aendeavor** [comment]
@cybermcm Alright, I'll re-open this issue. Thanks for letting me know.

Now to the matter at hand: You're definitely not the only one using sieve - unformtunately I am not using it. But to be honest, it seems like a misconfiguration on your side. What's the current status of this issue?

**Comment by cybermcm** [comment]
Status (just checked to be sure that it has the same status): I'm still struggling with the user filter.
What works? Putting a "before.dovecot.sieve" or "after.dovecot.sieve" in the config folder
What doesn't work? Putting a ".dovecot.sieve" in the user folder is still ignored and nothing happens...

**Comment by aendeavor** [comment]
I'm really not good at sieve etc. Maybe the wiki is outdated? Could it be that `.<FILE NAME>` files are ignored, due to the leading `.`?

**Comment by cybermcm** [comment]
Tried it when writing this issue and tried it now again even with no dot it isn't working....

**Comment by aendeavor** [comment]
Alright. Just for me, because I'm not an expert, not even close: What's wrong with User the `before` and `after`?

**Comment by cybermcm** [comment]
What's wrong: before and after are global rules effecting every user, I need rules for an individual user
other issues: nothing that helped me solve this
enabled: it's working globally, so I think it is enabled ;-) I've no idea how to disable/enable it for users (if this is even possible)

**Comment by aendeavor** [comment]
Thanks for the clarification. Sadly, I do not have the slightest clue...

I'll flag this a higher tier priority, maybe someone comes across.

**Comment by aendeavor** [comment]
Please note that this issue has become stale. As this repository is not maintained anymore, we are cleaning the issue tracker.

**Comment by cybermcm** [comment]
Still no clue how to achieve a user based sieve rule, I'd be happy if anyone can assist

**Comment by wernerfred** [comment]
Can you open a new Issue in the new project location (https://github.com/docker-mailserver/docker-mailserver) and put a ref to this issue?

**Comment by aendeavor** [comment]
> Can you open a new Issue in the new project location (https://github.com/docker-mailserver/docker-mailserver) and put a ref to this issue?

That would be a good idea, but the situation has just become very dynamic, since the owner of this repository just announced he could have migrated this repository. I'm currently thinking about that. Therefore, hold tight.

**Comment by cybermcm** [comment]
Thank you for moving my question to the new repository!

**Comment by aendeavor** [comment]
No problem:) Just as a reminder: There's now an action that labels and closed stale issues - just so you're not worried when the bot kicks in.

**Comment by cybermcm** [comment]
I'll keep the bot occupied ;-)

**Comment by cybermcm** [comment]
playing with the bot to keep it open....

**Comment by williamdes** [comment]
I can confirm Sieve filters works !

But I also found that this
```
if header :contains ["From"] "mail@domain.net" {
   fileinto "Archive";
} else {
     keep;
}
```

is not the same that
```
if allof (address :is "From" "mail@domain.net")
{
	fileinto "Archive";
} else {
     keep;
}
```

because if you send an email with the header `From: mail@domain.net` your rule will work, but not if it is sent as `From: Foo Bar  <mail@domain.net>`

**Comment by cybermcm** [comment]
@williamdes: thx for your answer but the rule itself works, from my post above:
```
working? Putting a "before.dovecot.sieve" or "after.dovecot.sieve" in the config folder
not working? Putting a ".dovecot.sieve" in the user folder is still ignored and nothing happens...
```
Did you try a "user sieve rule"?

**Comment by williamdes** [comment]
> @williamdes: thx for your answer but the rule itself works

I hope this will help someone, the RoundCube interface did not help a lot

> Did you try a "user sieve rule"?

No, sorry if that was the question on this issue :/

**Comment by cybermcm** [comment]
This thread is already long, just to summarize:
Sieve rules are working but only in 2 of 3 possible cases.
Case 1+2 working: global sieve rule ("before.dovecot.sieve" or "after.dovecot.sieve" in the config folder)
Case 3 not working: user sieve rule (.dovecot.sieve within /var/mail/domain/user)

**Comment by wernerfred** [comment]
But isn't case 3 the case I mentioned in my [comment](https://github.com/docker-mailserver/docker-mailserver/issues/1280#issuecomment-587349671)?
It places a `/var/mail/domain.tld/user/.dovecot_sieve` which works flawless since almost 2 years now.
Maybe we should compare the content and permissions. For me it seems like some weird behavior/configuration happened on your side as I have multiple instances of docker-mailserver in production and all work with sieve.

Which version are you using right now and did you change anything manually (through `user-patches.sh` or `config/`?

**Comment by cybermcm** [comment]
@wernerfred: thx for getting back for this topic.
my user sieve file (I think this has nothing to do with managed sieve)
```
require ["fileinto", "reject", "copy"];
if header :contains ["From"] "xxx@gmail.com" {
   fileinto "Junk";
}
```
it is placed in
/opt/docker/mail/var/TLD/USER/.dovecot.sieve
```
root@mail:/var/mail/TLD/USER# ls -la
total 196
drwx------ 15 docker docker  4096 Feb 20 18:13 .
drwxr-xr-x  5 docker docker  4096 Mar  7  2019 ..
drwx------  5 docker docker  4096 Sep 13 19:13 .Archive
drwx------  5 docker docker  4096 Feb 16 07:52 .Drafts
drwx------  5 docker docker  4096 Feb 20 18:14 .INBOX.Aggregate
drwx------  5 docker docker  4096 Dec 29 13:38 .INBOX.Forensic
drwx------  5 docker docker  4096 Dec 29 13:38 .INBOX.Invalid
drwx------  5 docker docker  4096 Dec 23  2018 .Junk
drwx------  5 docker docker  4096 Feb 16 08:53 .Sent
drwx------  5 docker docker  4096 Feb 20 11:15 .Trash
drwx------  5 docker docker  4096 Feb 20 13:46 .dmarc
-rw-------  1 docker docker   197 Oct 27 11:38 .dovecot.sieve
drwx------  2 docker docker  4096 Feb 20 18:12 cur
-rw-------  1 docker docker    39 Jun 29  2020 dovecot-keywords
-rw-------  1 docker docker   109 Feb 20 18:12 dovecot-uidlist
-rw-r--r--  1 docker docker     8 Dec 29 13:37 dovecot-uidvalidity
-rw-r--r--  1 docker docker     0 Oct 11  2018 dovecot-uidvalidity.5bbfa86c
-rw-------  1 docker docker  1264 Feb 20 11:14 dovecot.index
-rw-------  1 docker docker 25996 Feb 20 18:12 dovecot.index.cache
-rw-------  1 docker docker 31728 Feb 20 18:13 dovecot.index.log
-rw-------  1 docker docker 32804 Feb 19 13:47 dovecot.index.log.2
-rw-------  1 docker docker  1336 Feb 20 13:45 dovecot.list.index
-rw-------  1 docker docker  1476 Feb 20 16:39 dovecot.list.index.log
-rw-r--r--  1 docker docker  1728 Dec 29 13:38 dovecot.mailbox.log
drwx------  2 docker docker  4096 Feb 20 18:12 new
drwx------  2 docker docker  4096 Feb 20 18:11 sieve
-rw-------  1 docker docker    88 Dec 29 13:38 subscriptions
drwx------  2 docker docker  4096 Feb 20 18:12 tmp

```
and this is still not working

my changes in the config files (postfix-main.cf):
```
mynetworks=127.0.0.0/8 [::1]/128 [fe80::]/64 xxxx
smtp_use_tls = yes
smtp_enforce_tls = yes
smtpd_enforce_tls = yes
smtpd_tls_protocols = !SSLv2,!SSLv3
smtpd_tls_mandatory_protocols = !SSLv2,!SSLv3
```
working with the current  docker image "mailserver/docker-mailserver"

**Comment by wernerfred** [comment]
With current image i assume you mean `:edge`
what's inside your `sieve/`?

**Comment by cybermcm** [comment]
current = latest in my case
1. sieve/ is empty
2. I think there is a difference between the managed sieve service (you described in your comment) and simply put a sieve file in the /var/mail/TLD/USER folder
3. didn't try this because my user was already setup
4. tried your suggestions, both not working
5. root@mail:/# doveconf -f service=lda mail_plugins
mail_plugins =  sieve

**Comment by wernerfred** [comment]
Can you paste the output of this command run in the container: 
` cat /etc/dovecot/conf.d/90-sieve.conf | head -n 23`

**Comment by cybermcm** [comment]
```
root@mail:/# cat /etc/dovecot/conf.d/90-sieve.conf | head -n 23
##
## Settings for the Sieve interpreter
##

# Do not forget to enable the Sieve plugin in 15-lda.conf and 20-lmtp.conf
# by adding it to the respective mail_plugins= settings.

plugin {
  # The path to the user's main active script. If ManageSieve is used, this the
  # location of the symbolic link controlled by ManageSieve.
  sieve = ~/.dovecot.sieve

  # The default Sieve script when the user has none. This is a path to a global
  # sieve script file, which gets executed ONLY if user's private Sieve script
  # doesn't exist. Be sure to pre-compile this script manually using the sievec
  # command line tool.
  # --> See sieve_before fore executing scripts before the user's personal
  #     script.
  #sieve_default = /var/lib/dovecot/sieve/default.sieve

  # Directory for :personal include scripts for the include extension. This
  # is also where the ManageSieve service stores the user's scripts.
  sieve_dir = ~/sieve
```

**Comment by wernerfred** [comment]
I'm at the end of my wisdom. No clue why it is not working in your environments. Every option/config you provided looks exactly like mine.
Would it be possible for you to:
1. set up another clean instance and test or
2. use sth like rainloop (you can use my [image](https://github.com/wernerfred/docker-rainloop) to not hassle with configuration) to configure sieve if the user sieve is working then?

**Comment by cybermcm** [comment]
did some more digging...
1. clean instance: tried this with clean volumes but current compose config -> not working (user sieve rule)
2. tried to activate managesieve in roundcube -> not working, BUT it is not working because of a permission issue:
```
 Error: sieve: file storage: mkdir_parents_chgrp(/home/users/USER/sieve/tmp) failed: Permission denied (euid=5000(docker) egid=5000(docker) missing +w perm: /home, dir owned by 0:0 mode=0755)
```
I entered the mail container and set /home to `chmod go+w` and now managesieve is working (even test rules created in roundcube). rule is created in /home/users/USER/sieve/, I think that is not correct.
so my question: Is this the normal behavior? Maybe related to my LDAP config instead of "local" users

**Comment by wernerfred** [comment]
No this is the corret behaviour. Look at the output (especially the comments) of your comment: https://github.com/docker-mailserver/docker-mailserver/issues/1280#issuecomment-782727882

```
plugin {
  # The path to the user's main active script. If ManageSieve is used, this the
  # location of the symbolic link controlled by ManageSieve.
  sieve = ~/.dovecot.sieve
...
  # Directory for :personal include scripts for the include extension. This
  # is also where the ManageSieve service stores the user's scripts.
  sieve_dir = ~/sieve
```

**Comment by cybermcm** [comment]
Then I'm completely lost. According to the wiki:
```
All user defined sieve scripts that are managed by ManageSieve are stored in the user's home folder in /var/mail/domain.com/user1/sieve. Just one sieve script might be active for a user and is sym-linked to /var/mail/domain.com/user1/.dovecot.sieve automatically.
```
How does this fit to my finding that the rule is placed into /home/users/USER/sieve/?

**Comment by cybermcm** [comment]
Finally: Breakthrough!
I'm using this image for quite some time now and my LDAP was set up with the "postfix-book.schema"
There is an LDAP field called "mailHomeDirectory" which was set to "/home/users/USER".
Changing this to "/var/mail/TLD/USER" and now user sieve rule and Managesieve is working out of the box.

Thanks for all contributions and I'm more than happy to close the current oldest issue ;-)

**Comment by wernerfred** [comment]
Glad to help and happy that everything works now.
LDAP setups are tricky. One of my managed instances is also connected to LDAP and most of the wiki information doesn't fit my usecase. But with LDAP every setup is so special that it's hard to generalize (like you said - it starts that everyone can use different schema which will affect the whole further process)

**Comment by SebaFerraro** [comment]
I had the same problem and I could solve it by putting the following in the docker-compose.yml
 - DOVECOT_USER_ATTRS==home=/var/mail/%n,=mail=maildir:/var/mail/%n/Maildir,=uid=5000,=gid=5000
