### ISSUE TITLE
[FR] Create alias by sending an email to postmaster 

### ISSUE THREAD

**Issue by piwai** [docker-mailserver/docker-mailserver#1868]
# Feature Request

## Context

The postfix aliases are extremely useful when signing up to a lot of sites. Personally I create a new alias for each service to which I signup. This allows to quickly shutdown any address which gets compromised then spammed.
The thing is, I don't always have ssh access to my mail server, for example when I'm not at home, so I cannot connect and run the addalias and need to wait to sign up or (or resign and give my gmail address).

The general idea would be to be able to create an alias without having access to the container. I've studied some alternatives (detailled below), and since I always have access to a mail client (either on PC or smartphone), I realized that a solution could be to send a mail to a special address which would create the alias through a script.

### Is your Feature Request related to a Problem?

Nope.

### Describe the Solution you'd like

Sending an mail to "postmaster@domain.com" with subject "add alias foobar@domain.com myuser@domain.com " would trigger the "addalias" command and send an email to the newly created alias (to check that it works).

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

That being said, just tell me now if this has no chances of ever being merged so I don't waste my time :-)

### What are you going to contribute??

To be discussed, not sure what changes this would require, for example in terms of account / permission. ( /tmp/docker-mailserver/postfix-virtual.cf is owned by root so this would need to be changed to be writable by the user configured in master.cf transport) 

### Alternatives you've considered

 * Postfix builtin "plus addressing" (user+foo@domain, user+bar@domain)" to avoid creating aliases. Drawbacks:
    * it's easy for spammers to strip the +xxx so less effective than a complete alias in my opinion
    * I've seen some websites refusing to sign up when there was a "+" in the email (they probably tried to [validate the mail with a regex](https://stackoverflow.com/questions/201323/how-to-validate-an-email-address-using-a-regular-expression)...) 
 
 * Developing a full android app to handle ssh connection to the mail server and running the commands. Drawbacks:
    *  quite a lot more work
    *  security (would need to have ssh key to the server stored on my smartphone)

 * Installing postfixadmin . Drawbacks
   *  requires a SQL database
   *  => #1512 :-)

### Who will that Feature be useful to?

Difficult to say, but I guess this could be useful to all other people around there who create an alias per service.

### What have you done already?

Reading documentation on how to route emails to a script:
https://serverfault.com/questions/322657/how-can-i-route-some-emails-to-a-script-in-postfix

**Comment by casperklein** [comment]
Take a look at `procmail`. It should provide the feature your are looking for :+1:

**Comment by piwai** [comment]
@casperklein thanks for the suggestion! Clearly I overlooked this approach, as I thought procmail / dovecot sieve only allowed to redirect to a specific folder or do basic SMTP header processing. 

Since I'm already using sieve to perform filtering into folders, I tried the "vnd.dovecot.pipe" extension as explained [here](https://github.com/docker-mailserver/docker-mailserver/blob/master/docs/content/config/advanced/mail-sieve.md) and it works great (after I realized the /tmp/docker-mailserver/sieve-pipe/ is copied in /usr/lib/dovecot/sieve-pipe/ only on container startup and I cannot edit the script from outside the container...)
Now I need to properly secure the pipe script and sanitize the inputs :-)

**Comment by casperklein** [comment]
I am glad to here that you found a solution.

If you think, some information in our documentation is missing or could be better explained, it would be great if you could provide some lines 😉 

As this is solved, we can close this issue?

**Comment by wernerfred** [comment]
> * Postfix builtin "plus addressing" (user+foo@domain, user+bar@domain)"

Just for Information: It is possible to change this delimiter to another character of your choice. See [docs](https://docker-mailserver.github.io/docker-mailserver/edge/config/user-management/aliases/#address-tags-extension-delimiters-an-alternative-to-aliases)

You could use temp@domain.tld as your "main" address for such purposes and then use (without further configuration) any mail using the delimiter. E.g. temp-newsletterA@domain.tld (if your delimiter is `-`)
If it gets compromised you could manually add the address as a send-only/reject-incoming address or use sieve filters to block them.

Moving the mails from the "aliases" to your main mail could be done by sieve (accessible via webmail if you have one in place).

@piwai  Other then that, can we close the issue?

**Comment by piwai** [comment]
@wernerfred 

yep, thanks for the details. I didn't mention it but actually I'm already using this ("plus addressing" with "-" instead of "+" as a delimiter) since a few months for some new aliases. Works great, but still not sure if I want to go with plus addressing only and migrate *all* my aliases to this new format, then keep just one and use only extensions after the delimiter, which would indeed eliminate the need of this aliasbot. 

The thing which bothers me with this setup is if the "main" mailbox get compromised, it won't be easy to change it, so my idea was to combine both aliases and plus addressing: use aliases for general categories like "forums", "shopping", "code", "bank", "health", "providers", etc... then put the service name as the extension. 
And also it's easier to check which mailboxes are active if they're all aliases, because they will be the exhaustive list in postfix config, while with plus addressing you can't easily check the addresses in use, unless you create a distinct folder for each one, which I'm not a big fan as I would like to keep the folders matching the categories described earlier.

But in the end maybe it's just me being paranoid about spam and overthinking the problem. Anyway, I get very few "compromised" address but one of them is the one is use for github because it's public, and I still haven't updated it :sweat: 
 
So yes, this issue can be closed. If I ever implement the aliasbot, I may submit a small PR to keep the filed ordered when adding a new alias.
