### ISSUE TITLE
bug report: Mail Server behind Traefik, Fetchmail fails to deliver incoming mails

### ISSUE THREAD

**Issue by pdehne** [docker-mailserver/docker-mailserver#4058]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I am trying to setup docker-mailserver behind Traefik, following https://docker-mailserver.github.io/docker-mailserver/latest/examples/tutorials/mailserver-behind-proxy/

For one of my domains I use regular smtp for incoming mail, for other domains I use fetchmail to collect the incoming mails.

To allow fetchmail to forward mails to smtp I followed the section "Configuring services with separate ports for PROXY protocol" in the Tutorials page. I needed it for smtp only. Therefore I added to user-patches.sh:

```
postconf -Mf smtp/inet | sed -e s/^smtp/12525/ >> /etc/postfix/master.cf
postconf -P 12525/inet/postscreen_upstream_proxy_protocol=haproxy 12525/inet/syslog_name=smtp-proxyprotocol
```

With both docker-mailserver 13 and 14 I see the the following errors in mail.log:

```
2024-06-09T09:32:05.682662+02:00 mail postfix/postscreen[2972]: fatal: btree:/var/lib/postfix/postscreen_cache: unable to get exclusive lock: Resource temporarily unavailable
2024-06-09T09:32:06.683464+02:00 mail postfix/master[1089]: warning: process /usr/lib/postfix/sbin/postscreen pid 2972 exit status 1
2024-06-09T09:32:06.683475+02:00 mail postfix/master[1089]: warning: /usr/lib/postfix/sbin/postscreen: bad command startup -- throttling
```

With docker-mailserver 13 mails from fetchmail get delivered.

With docker-mailserver 14 mails from fetchmail no longer get delivered and I get the following additional errors in mail.log:

```
2024-06-09T09:30:54.183619+02:00 mail fetchmail[1107]: reading message mysonicwebde@mail.gbc.net:1 of 1 (9929 header octets) (log message incomplete)
2024-06-09T09:30:54.183630+02:00 mail fetchmail[1107]: SMTP connect to localhost failed
2024-06-09T09:30:54.206819+02:00 mail fetchmail[1107]: SMTP transaction error while fetching from mysonicwebde@mail.gbc.net and delivering to SMTP host localhost
```

### 🐋 DMS Version

v13.3.1 and v14

### 💻 Operating System and Architecture

Debian 11 (Bullseye) amd64

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:13
    container_name: mailserver
    restart: unless-stopped
    stop_grace_period: 1m
    hostname: mail.dehne-cloud.de # FQDN des Mailservers. Der DNS MX Record muss auf diesen Host zeigen.

    # Kommentar entfernen falls `ENABLE_FAIL2BAN=1` gesetzt wird:
    cap_add:
      - NET_ADMIN
    
    networks:
      - traefik
    
    # Ports
    
    # Die Ports werden durch Traefik veröffentlicht nicht von diesem Container

    # Details zu den Ports und wie sie verwendet werden:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    
    # ports:
      # - "25:25" # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      # - "143:143" # IMAP4 (explicit TLS => STARTTLS), deaktiviert
      # - "465:465" # ESMTP (implicit TLS)
      # - "587:587" # ESMTP (explicit TLS => STARTTLS), deaktiviert
      # - "993:993" # IMAP4 (implicit TLS)

    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

    env_file: mailserver.env

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - dms-mail-config:/tmp/docker-mailserver/
      - dms-mail-data:/var/mail/
      - dms-mail-logs:/var/log/mail/
      - dms-mail-state:/var/mail-state/
      - traefik-certificates:/etc/letsencrypt # Verzeichnis für Zertifikate
    
    labels:
      - "traefik.enable=true"

      # SMTP
      - traefik.tcp.routers.mail-smtp.entrypoints=mail-smtp
      - traefik.tcp.routers.mail-smtp.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-smtp.service=mail-smtp
      # In user-patches.sh wird eine Kopie von Port 25 auf Port 12525 erstellt und die ProxyProtocol Unterstützung aktiviert
      # Traefik leitet zu Postfix Port 12525 weiter
      # Für den Docker internen Datenverkehr kann Port 25 weiterhin ohne Proxy Unterstützung verwendet werden
      - traefik.tcp.services.mail-smtp.loadbalancer.server.port=12525
      - traefik.tcp.services.mail-smtp.loadbalancer.proxyProtocol.version=2 # Postfix unterstützt Version 2
      # Kein TLS, da Traefik den STARTTLS Vorgang nicht unterstützt, Postfix behandelt STARTTLS selbst

      # ESMTP (implicit TLS), mit optionaler HostSNI Unterstützung
      - traefik.tcp.routers.mail-submissions.entrypoints=mail-submissions
      - traefik.tcp.routers.mail-submissions.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-submissions.service=mail-submissions
      - traefik.tcp.routers.mail-submissions.tls.passthrough=true # Traefik soll TLS nicht terminieren
      - traefik.tcp.services.mail-submissions.loadbalancer.server.port=465
      - traefik.tcp.services.mail-submissions.loadbalancer.proxyProtocol.version=2 # Postfix unterstützt Version 2

      # IMAP4 (implicit TLS), mit optionaler HostSNI Unterstützung
      # Dovecot wird so konfiguriert das es auf Port 10993 hört, um Konflikte mit internen Systemen wie postscreen
      # und amavis zu vermeiden, die auf den Standardports kommunizieren.
      - traefik.tcp.routers.mail-imaps.entrypoints=mail-imaps
      - traefik.tcp.routers.mail-imaps.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-imaps.service=mail-imaps
      - traefik.tcp.routers.mail-imaps.tls.passthrough=true # Traefik soll TLS nicht terminieren
      - traefik.tcp.services.mail-imaps.loadbalancer.server.port=10993 # Traefik leitet verschlüsselt zu Dovecots Port 10993 weiter
      - traefik.tcp.services.mail-imaps.loadbalancer.proxyProtocol.version=2 # Dovecot unterstützt Version 2

volumes:
  dms-mail-config:
    external: true
  dms-mail-data:
    external: true
  dms-mail-logs:
    external: true
  dms-mail-state:
    external: true
  traefik-certificates:
    external: true

networks:
  traefik:
    external: true
```

### 📜 Relevant log output

```Text
2024-06-09T09:32:05.682662+02:00 mail postfix/postscreen[2972]: fatal: btree:/var/lib/postfix/postscreen_cache: unable to get exclusive lock: Resource temporarily unavailable
2024-06-09T09:32:06.683464+02:00 mail postfix/master[1089]: warning: process /usr/lib/postfix/sbin/postscreen pid 2972 exit status 1
2024-06-09T09:32:06.683475+02:00 mail postfix/master[1089]: warning: /usr/lib/postfix/sbin/postscreen: bad command startup -- throttling
...
2024-06-09T09:30:54.183619+02:00 mail fetchmail[1107]: reading message mysonicwebde@mail.gbc.net:1 of 1 (9929 header octets) (log message incomplete)
2024-06-09T09:30:54.183630+02:00 mail fetchmail[1107]: SMTP connect to localhost failed
2024-06-09T09:30:54.206819+02:00 mail fetchmail[1107]: SMTP transaction error while fetching from mysonicwebde@mail.gbc.net and delivering to SMTP host localhost
```

**Comment by pdehne** [comment]
Nice to have AI answering right away, probably asking mit to double check some related configuration. But sorry, I don't understand Spanish :-)

**Comment by polarathene** [comment]
The AI responding in Spanish is a known issue, hopefully it'll be resolved by Glime otherwise we may have to remove it.

---

I've not got much time to assist unfortunately, but I do recall fetchmail is configured to interact with `127.0.0.1:25` IIRC?

- We start the daemon service [here](https://github.com/docker-mailserver/docker-mailserver/blob/18d9d1adcc479b7a38a31780a363c8ed272da32b/target/supervisor/conf.d/dms-services.conf#L126)
- Startup script related to it is [here](https://github.com/docker-mailserver/docker-mailserver/blob/18d9d1adcc479b7a38a31780a363c8ed272da32b/target/scripts/startup/setup.d/fetchmail.sh).
- DMS fetchmail docs were rewritten for v14: https://docker-mailserver.github.io/docker-mailserver/v14.0/config/advanced/mail-fetchmail/
- Official upstream [fetchmail docs here](https://www.fetchmail.info/fetchmail-man.html#delivery-control-options).

The upstream docs note that by default it will deliver to `localhost` if no explicit host is configured.

- `--smtphost` as an option added to the daemon service presumably would let you specify an alternative IP + port.
- Another option if you don't need to deliver to Postfix would be to deliver directly to Dovecot via LMTP (_which is what Postfix uses_), but I'm not sure if that is advisable to skip processing the mail through Postfix first before it hands off to Dovecot.

---

I can see that you followed the advice for the separate PROXY protocol variant of port 25:

> ![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/dfa888a5-050f-413d-acbb-d62ba79dd6e6)

I recall a difference between Dovecot and Postfix when I wrote those docs. I think Dovecot allowed/required a subnet for trusted hosts, while Postfix didn't have any equivalent (everyone trusted). I'm not 100% sure though if that is relevant to the issue you're facing.

Presumably port 25 should be fine and not require a PROXY protocol header. Yet `postscreen` as per your logs suggests it's getting bad data (_[here is what it should look like](https://github.com/docker-mailserver/docker-mailserver/blob/18d9d1adcc479b7a38a31780a363c8ed272da32b/target/postfix/master.cf#L13-L14) without the `user-patches.sh` changes_). Double check that `/etc/postfix/master.cf` is looking alright?

---

> `/var/lib/postfix/postscreen_cache: unable to get exclusive lock: Resource temporarily unavailable`

Could you temporarily disable your `mail-state` volume mount?

Make sure you start a fresh container instance, not lingering state from a previous run (_`docker compose up --force-recreate` or equivalent_). If it's a `/var/lib` issue this should resolve any issues there from the volume and helps pin that down.

I vaguely recall a concern with the PROXY protocol and `127.0.0.1` / `localhost` connections. It was probably as I had highlighted in the docs with the separate ports, so I'm at a loss as to why that's breaking for you 🤔

**Comment by pdehne** [comment]
Many thanks for your very quick reply and the pointers where I can double check. I am out for the rest of the day, but I will dig into this this evening. Many thanks again!

**Comment by pdehne** [comment]
All tests where done on v13.3.1. I will make the same tests with v14. So, even though the below messages appear in the log delivering with fetchmail still works. Therefore the errors and warnings may be unrelated to the problem with fetchmail not delivering mail with v14.

I disabled the `mail-state` and made sure to recreate the container. I still get the same log messages.

```
Jun  9 21:02:43 mail smtp-proxyprotocol/postscreen[3113]: fatal: btree:/var/lib/postfix/postscreen_cache: unable to get exclusive lock: Resource temporarily unavailable
Jun  9 21:02:44 mail postfix/master[914]: warning: process /usr/lib/postfix/sbin/postscreen pid 3113 exit status 1
Jun  9 21:02:44 mail postfix/master[914]: warning: /usr/lib/postfix/sbin/postscreen: bad command startup -- throttling
```

Then I commented out everything in user-patches.sh. The log messages above no longer showed up. After I reactivated my changes in user-patches.sh the log messages reappeared.

This is in my user-patches.sh, straight from the tutorial page:

```
#!/bin/bash

# 465 auf Port 10465
postconf -Mf submissions/inet | sed -e s/^submissions/10465/ -e 's/submissions/submissions-proxyprotocol/' >> /etc/postfix/master.cf

# Fuer Port 10465 PROXY Protokoll aktivieren
postconf -P 10465/inet/smtpd_upstream_proxy_protocol=haproxy

# 25 auf Port 12525
postconf -Mf smtp/inet | sed -e s/^smtp/12525/ >> /etc/postfix/master.cf

# Fuer Port 12525 PROXY Protokoll aktivieren
postconf -P 12525/inet/postscreen_upstream_proxy_protocol=haproxy 12525/inet/syslog_name=smtp-proxyprotocol

echo '[   INF   ]  user-patches.sh successfully executed'
```

I did not add an entry for port 587 to 10587 with proxy protocol because we don't expose 587 anyway.

`postfix-master.cf` is empty.

`postfix-main.cf`just enables SMTPS wrapper mode for outgoing mail:

```
# Ermögliche SMTPS wrappermode (TCP port 465)
smtp_tls_wrappermode = yes
smtp_tls_security_level = encrypt
```

**Comment by pdehne** [comment]
Tests with v14.

Fetchmail still works this time. I am sadly not sure what has changed compared to my very first reporting.

The errors for smtp-proxyprotocol/postscreen are still coming up though.

```
2024-06-09T22:52:26.333958+02:00 mail smtp-proxyprotocol/postscreen[5533]: fatal: btree:/var/lib/postfix/postscreen_cache: unable to get exclusive lock: Resource temporarily unavailable
2024-06-09T22:52:27.334622+02:00 mail postfix/master[1065]: warning: process /usr/lib/postfix/sbin/postscreen pid 5533 exit status 1
2024-06-09T22:52:27.334635+02:00 mail postfix/master[1065]: warning: /usr/lib/postfix/sbin/postscreen: bad command startup -- throttling
```

After testing with Fetchmail, I double checked proxied smtp 25 -> 12525 and this stopped working. Which probably makes sense with the above error messages.

**Comment by pdehne** [comment]
I found a workaround. I just followed the tutorial and proxied the existing ports. Then I changed Fetchmail to forward mails to the Traefik reverse proxy, not localhost. This way all incoming mail goes through Traefik and there is no need for separate smtp, one with and one without proxy protocol support.

If there are other services that are trying to talk using smtp on localhost / directly to the docker-mailserver, without proxy support, that could become a problem. I haven't seen that in my tests so far though.

As long as everything can be configured to go through the Traefik reverse proxy, the following configuration should work.

docker-compose.yml

```
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:14
    container_name: mailserver
    restart: unless-stopped
    stop_grace_period: 1m
    hostname: ************** # FQDN des Mailservers. Der DNS MX Record muss auf diesen Host zeigen.

    # Kommentar entfernen falls `ENABLE_FAIL2BAN=1` gesetzt wird:
    cap_add:
      - NET_ADMIN
    
    networks:
      - traefik
    
    # Ports
    
    # Die Ports werden durch Traefik veröffentlicht nicht von diesem Container

    # Details zu den Ports und wie sie verwendet werden:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    
    # ports:
      # - "25:25" # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      # - "143:143" # IMAP4 (explicit TLS => STARTTLS), deaktiviert
      # - "465:465" # ESMTP (implicit TLS)
      # - "587:587" # ESMTP (explicit TLS => STARTTLS), deaktiviert
      # - "993:993" # IMAP4 (implicit TLS)

    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

    env_file: mailserver.env

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - dms-mail-config:/tmp/docker-mailserver/
      - dms-mail-data:/var/mail/
      - dms-mail-logs:/var/log/mail/
      - dms-mail-state:/var/mail-state/
      - traefik-certificates:/etc/letsencrypt # Verzeichnis für Zertifikate
    
    labels:
      - "traefik.enable=true"

      # SMTP
      - traefik.tcp.routers.mail-smtp.entrypoints=mail-smtp
      - traefik.tcp.routers.mail-smtp.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-smtp.service=mail-smtp
      - traefik.tcp.services.mail-smtp.loadbalancer.server.port=25
      - traefik.tcp.services.mail-smtp.loadbalancer.proxyProtocol.version=2
      # Kein TLS, da Traefik den STARTTLS Vorgang nicht unterstützt, Postfix behandelt STARTTLS selbst

      # ESMTP (implicit TLS), mit optionaler HostSNI Unterstützung
      - traefik.tcp.routers.mail-submissions.entrypoints=mail-submissions
      - traefik.tcp.routers.mail-submissions.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-submissions.service=mail-submissions
      - traefik.tcp.routers.mail-submissions.tls.passthrough=true # Traefik soll TLS nicht terminieren
      - traefik.tcp.services.mail-submissions.loadbalancer.server.port=465
      - traefik.tcp.services.mail-submissions.loadbalancer.proxyProtocol.version=2

      # IMAP4 (implicit TLS), mit optionaler HostSNI Unterstützung
      # Dovecot wird so konfiguriert das es auf Port 10993 hört, um Konflikte mit internen Systemen wie postscreen
      # und amavis zu vermeiden, die auf den Standardports kommunizieren.
      - traefik.tcp.routers.mail-imaps.entrypoints=mail-imaps
      - traefik.tcp.routers.mail-imaps.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-imaps.service=mail-imaps
      - traefik.tcp.routers.mail-imaps.tls.passthrough=true # Traefik soll TLS nicht terminieren
      - traefik.tcp.services.mail-imaps.loadbalancer.server.port=10993 # Traefik leitet verschlüsselt zu Dovecots Port 10993 weiter
      - traefik.tcp.services.mail-imaps.loadbalancer.proxyProtocol.version=2

volumes:
  dms-mail-config:
    external: true
  dms-mail-data:
    external: true
  dms-mail-logs:
    external: true
  dms-mail-state:
    external: true
  traefik-certificates:
    external: true

networks:
  traefik:
    external: true
```

postfix-master.cf

```
smtp/inet/postscreen_upstream_proxy_protocol=haproxy
submissions/inet/smtpd_upstream_proxy_protocol=haproxy
```

fetchmailrc

```
set postmaster "******" # postmaster is this email adress
set no bouncemail # Direct error mail to postmaster rather than sender
set no spambounce

poll "********" aka "********" with protocol IMAP service 993 no dns localdomains *********** ************
        user "**********" with password "*********" to * here
        fetchall
        smtphost traefik # hostname of the Traefik reverse proxy
        ssl
        no keep
```

user-patches.sh is empty / can be deleted.

**Comment by polarathene** [comment]
> `postfix-main.cf`just enables SMTPS wrapper mode for outgoing mail:
> 
> ```
> # Ermögliche SMTPS wrappermode (TCP port 465)
> smtp_tls_wrappermode = yes
> smtp_tls_security_level = encrypt
> ```

I am not sure why you set this?

Port 25 outbound is not meant to be with implicit TLS like you configure here, only port 465.

Port 465 is no longer associated to SMTPS, but Submissions. Other mail servers will not respond well to connections on port 25 when they expect plain-text / StartTLS, not TLS immediately. If you are only connecting outbound to a relay service which supports implicit TLS, then this is a non-issue.

---

> `smtphost traefik # hostname of the Traefik reverse proxy`

Ah nice, it is also a config option. Good to know you could set that there without having to workaround the supervisord config.

---

I requested you to check `/etc/postfix/master.cf` in the container. This is what the scripts were modifying, your `postscreen` issue may have been due to that.

I did not extensively test when I wrote those docs, so it's possible that `postscreen` doesn't properly support both PROXY protocol and non-PROXY protocol connections 🤷‍♂️

**Comment by pdehne** [comment]
> If you are only connecting outbound to a relay service which supports implicit TLS, then this is a non-issue.

That's exactly what I am doing :-)

> I requested you to check /etc/postfix/master.cf in the container.
> This is what the scripts were modifying, your postscreen issue may have been due to that.

Sorry I overlooked that. I switched back to the previous config with a separate set of services with proxy enabled. This is what has been added at the end of `/etc/postfix/master.cf`:

```
...
10465      inet  n       -       n       -       -       smtpd
    -o syslog_name=postfix/submissions-proxyprotocol
    -o smtpd_tls_wrappermode=yes
    -o smtpd_sasl_auth_enable=yes
    -o smtpd_sasl_type=dovecot
    -o smtpd_reject_unlisted_recipient=no
    -o smtpd_sasl_authenticated_header=yes
    -o smtpd_client_restrictions=permit_sasl_authenticated,reject
    -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
    -o smtpd_sender_restrictions=$mua_sender_restrictions
    -o smtpd_discard_ehlo_keywords=
    -o milter_macro_daemon_name=ORIGINATING
    -o cleanup_service_name=sender-cleanup
    -o smtpd_upstream_proxy_protocol=haproxy
12525      inet  n       -       n       -       1       postscreen
    -o postscreen_upstream_proxy_protocol=haproxy
    -o syslog_name=smtp-proxyprotocol
```

**Comment by pdehne** [comment]
I think I found the solution. I am way out of my knowledge zone so feel free to correct me :-)

After creating the additional set of services that have proxy protocol enabled there are two postscreen services. Both try to get an exclusive lock on postscreen_cache which is not supported by default and fails.

To fix this the manual says to prefix the default postscreen_cache_map setting with `proxy:`. See https://www.postfix.org/postconf.5.html#postscreen_cache_map for reference.

This can be achieved by adding the following line to `postfix-main.cf`:

```
postscreen_cache_map = proxy:btree:$data_directory/postscreen_cache
```

After this the error messages no longer appeared and both incoming mail through Traefik (proxied) and Fetchmail (localhost, not proxied) started to work.

Here is the rest of my final working config for reference.

user-patches.sh

```
#!/bin/bash

postconf -Mf submissions/inet | sed -e s/^submissions/10465/ -e 's/submissions/submissions-proxyprotocol/' >> /etc/postfix/master.cf
postconf -P 10465/inet/smtpd_upstream_proxy_protocol=haproxy

postconf -Mf smtp/inet | sed -e s/^smtp/12525/ >> /etc/postfix/master.cf
postconf -P 12525/inet/postscreen_upstream_proxy_protocol=haproxy 12525/inet/syslog_name=smtp-proxyprotocol

echo '[   INF   ]  user-patches.sh successfully executed'
```

postfix-master.cf is empty.

fetchmail.cf

```
set postmaster "**********" # postmaster is this email address
set no bouncemail # Direct error mail to postmaster rather than sender
set no spambounce

poll "************" aka "*************" with protocol IMAP service 993 no dns localdomains ************ ***********
        user "**********" with password "**********" to * here
        fetchall
        smtphost localhost
        ssl
        no keep
```

dovecot.cf

```
haproxy_trusted_networks = 172.21.0.4
haproxy_timeout = 3 secs
service imap-login {
  inet_listener imaps {
    haproxy = yes
    ssl = yes
    port = 10993
  }
}
```

docker-compose.yml

```
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:14
    container_name: mailserver
    restart: unless-stopped
    stop_grace_period: 1m
    hostname: ********** # FQDN des Mailservers. Der DNS MX Record muss auf diesen Host zeigen.

    cap_add:
      - NET_ADMIN
    
    networks:
      - traefik
    
    # Ports
    
    # ports:
      # - "25:25" # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      # - ":12525" # SMTP mit Proxy Unterstützung
      # - "143:143" # IMAP4 (explicit TLS => STARTTLS), deaktiviert
      # - "465:465" # ESMTP (implicit TLS)
      # - ":10465" # ESMTP (implicity TLS) mit Proxy Unterstützung
      # - "587:587" # ESMTP (explicit TLS => STARTTLS), deaktiviert
      # - "993:993" # IMAP4 (implicit TLS)
      # - ":10993" # IMAP4 (implicit TLS) mit Proxy Unterstützung

    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

    env_file: mailserver.env

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - dms-mail-config:/tmp/docker-mailserver/
      - dms-mail-data:/var/mail/
      - dms-mail-logs:/var/log/mail/
      - dms-mail-state:/var/mail-state/
      - traefik-certificates:/etc/letsencrypt # Verzeichnis für Zertifikate
    
    labels:
      - "traefik.enable=true"

      # SMTP
      - traefik.tcp.routers.mail-smtp.entrypoints=mail-smtp
      - traefik.tcp.routers.mail-smtp.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-smtp.service=mail-smtp
      - traefik.tcp.services.mail-smtp.loadbalancer.server.port=12525
      - traefik.tcp.services.mail-smtp.loadbalancer.proxyProtocol.version=2
      # Kein TLS, da Traefik den STARTTLS Vorgang nicht unterstützt, Postfix behandelt STARTTLS selbst

      # ESMTP (implicit TLS), mit optionaler HostSNI Unterstützung
      - traefik.tcp.routers.mail-submissions.entrypoints=mail-submissions
      - traefik.tcp.routers.mail-submissions.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-submissions.service=mail-submissions
      - traefik.tcp.routers.mail-submissions.tls.passthrough=true # Traefik soll TLS nicht terminieren
      - traefik.tcp.services.mail-submissions.loadbalancer.server.port=10465
      - traefik.tcp.services.mail-submissions.loadbalancer.proxyProtocol.version=2

      # IMAP4 (implicit TLS), mit optionaler HostSNI Unterstützung
      - traefik.tcp.routers.mail-imaps.entrypoints=mail-imaps
      - traefik.tcp.routers.mail-imaps.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-imaps.service=mail-imaps
      - traefik.tcp.routers.mail-imaps.tls.passthrough=true # Traefik soll TLS nicht terminieren
      - traefik.tcp.services.mail-imaps.loadbalancer.server.port=10993 # Traefik leitet verschlüsselt zu Dovecots Port 10993 weiter
      - traefik.tcp.services.mail-imaps.loadbalancer.proxyProtocol.version=2

volumes:
  dms-mail-config:
    external: true
  dms-mail-data:
    external: true
  dms-mail-logs:
    external: true
  dms-mail-state:
    external: true
  traefik-certificates:
    external: true

networks:
  traefik:
    external: true
```

**Comment by polarathene** [comment]
> I think I found the solution. I am way out of my knowledge zone so feel free to correct me :-)
> 
> After creating the additional set of services that have proxy protocol enabled there are two postscreen services. Both try to get an exclusive lock on postscreen_cache which is not supported by default and fails.
> 
> To fix this the manual says to prefix the default postscreen_cache_map setting with `proxy:`. See https://www.postfix.org/postconf.5.html#postscreen_cache_map for reference.
> 
> This can be achieved by adding the following line to `postfix-main.cf`:
> 
> ```
> postscreen_cache_map = proxy:btree:$data_directory/postscreen_cache
> ```
> 
> After this the error messages no longer appeared and both incoming mail through Traefik (proxied) and Fetchmail (localhost, not proxied) started to work.

Excellent! Thanks for sharing that solution ❤️ 

This looks ok to me glancing over the docs. I can add this as an additional step on our docs for supporting multiple ports, does that seem acceptable for resolving this issue?

**Comment by pdehne** [comment]
> does that seem acceptable for resolving this issue?

Yes! Many thanks again for you help. Feel free to close this issue.
